In [ ]:
import pandas as pd
import numpy as np
# numpy는 숫자 배열만 처리 가능 (1차원 vector list / 2차원 array)
# pandas : series(1차원 배열 = vector = list = value가 1개인 dictionary), dataframe(2차원 배열 = value가 2개 이상 dictionary)을 처리 가능 /

In [ ]:
#Series
obj = pd.Series([4, 7, -5, 3])
print(obj) #맨 앞의 열은 index
print(obj[0])

0    4
1    7
2   -5
3    3
dtype: int64
4

In [ ]:
arr = obj.to_numpy() #1차원 배열
print(arr)
print(obj)
print(obj.index)
print(np.sum(obj))
print(np.sum(arr))

[ 4  7 -5  3]
0    4
1    7
2   -5
3    3
dtype: int64
RangeIndex(start=0, stop=4, step=1)
9
9

In [ ]:
obj = pd.Series([4, 7, -5, 3], index = ['a', 'b','c','d'])
print(obj)
print(obj['a']) #명시적 index
#print(obj[0]) 암시적 index. series에서 사용은 가능하지만 권장하지 않음
l = [1,2,3,4]
print(l[0])
#print(l[0,1,2]) error
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[[0,1,2]])
print(obj[['a','b','c']]) #numpy, pandas에서 여러개의 index를 가져오는 것이 가능

a    4
b    7
c   -5
d    3
dtype: int64
4
1
1
[1 2 3]
a    4
b    7
c   -5
dtype: int64

In [ ]:
print(arr[arr>2]) #bool index
print(obj[obj>2])

[3 4]
a    4
b    7
d    3
dtype: int64

In [ ]:
#in 연산자 : index의 존재를 확인
print('a' in obj)
print(0 in obj) #암시적 index는 검색이 불가함
print('e' in obj)

True
False
False

In [ ]:
#dictionary를 이용한 series : dictionary의 key가 series의 index가 됨
dic = obj.to_dict()
print(dic)
sdata = pd.Series({"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000})
print(sdata)
dic1 = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
sdata1 = pd.Series({"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}) ; sdata1 = pd.Series(dic1)
print(sdata1)

{'a': 4, 'b': 7, 'c': -5, 'd': 3}
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
dic1 = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
sdata1 = pd.Series(dic1, index = ["California", "Ohio", "Oregon", "Texas"])
print(sdata1)
print(pd.isna(sdata1))
print(pd.notna(sdata1))
print(sdata1.isna())

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
#연산
print(sdata)
print(sdata1)
print(sdata + sdata1) #index 기준으로 연산이 진행됨. NaN 값의 합은 NaN

sdata.name = "이다현"
sdata.index.name ='state'
print(sdata)

#index 순서 변경
sdata.index=['Ohio','Oregon','Texas','Utah']
print(sdata)

state
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
Name: 이다현, dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64
state
Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
Name: 이다현, dtype: int64
Ohio      35000
Oregon    71000
Texas     16000
Utah       5000
Name: 이다현, dtype: int64

In [ ]:
#dataframe
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)
print(df)
df.head() #5개 행
df.head(n=3)
df.tail()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
#열 순서 변경 및 dataframe 생성
df1 = pd.DataFrame(data, columns = ["year", "state", "pop"])
print(df1)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
df2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])
print(df2)
print(df2['state'])
print(type(df2['state']))

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN
0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#행출력
print(df2)
print(df2['year'])
#print(df2[0]) error
print(df2.loc[0])
print(df2.iloc[2]) #iloc는 암시적 index
print(df2.iloc[-4]) #
#print(df2.loc[-4]) #error. 명시적 index에서는 -를 사용할 수 없으

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN
0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64
year     2000
state    Ohio
pop       1.5
debt      NaN
Name: 0, dtype: object

In [ ]:
print(df2)
df2['debt'] = 16.5
print(df2)

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN
   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [ ]:
df2['debt'] = np.arange(6,) #0~5의 값을 순차적으로 채움
print(df2)

   year   state  pop  debt
0  2000    Ohio  1.5     0
1  2001    Ohio  1.7     1
2  2002    Ohio  3.6     2
3  2001  Nevada  2.4     3
4  2002  Nevada  2.9     4
5  2003  Nevada  3.2     5

In [ ]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
print(val)
df2['debt'] = val
df2 #같은 index에 할당됨

2   -1.2
4   -1.5
5   -1.7
dtype: float64

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [ ]:
#bool index
print(df2["state"] == "Ohio")
df2["eastern"] = df2["state"] == "Ohio" #열추가
df2
#dictionary와 동일하게 열(key)이 있는 경우 수정, 열이 없는 경우 추가

0     True
1     True
2     True
3    False
4    False
5    False
Name: state, dtype: bool

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [ ]:
print(df2)
print(df2['eastern'])
del df2['eastern']
df #이미 없앤 열을 두 번 없애기 실행하면 error

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False
0     True
1     True
2     True
3    False
4    False
5    False
Name: eastern, dtype: bool

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
print(df2.columns)#colum의 이름을 출력

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
df3 = pd.DataFrame(populations)
print(df3) #value를 dictionary로 부여할 수 있음
print(df3.T)

df4 = pd.DataFrame(populations, index=[2001,2002,2003])
print(df4)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9
      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [ ]:
#bool index
print(df3)
print(df3['Ohio'][2001])
print(df3['Ohio'][:])
print(df3['Ohio'][:-1]) #2002전까지 . 암시적 index 사용

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9
1.7
2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64
2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [ ]:
print(df3)
pdata = {"Ohio": df3["Ohio"][:-1],
         "Nevada" : df3["Nevada"][:-1]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [ ]:
df3.name = "K"
df3.columns.name = 'city'
df3.index.name = 'year'
df3

city  Ohio  Nevada
year
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [ ]:
df3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [ ]:
print("Ohio" in df3.columns)
print(2001 in df3.index)
print(df3.columns)

True
True
Index(['Ohio', 'Nevada'], dtype='object', name='city')

In [ ]:
#reindexting
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj
obj2 = obj.reindex(["a", "b", "c", "d", "e"]) #index 순서 변경
print(obj2)

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
print(obj3)
reindexed = obj3.reindex(np.arange(6), method="ffill") #앞의값을 뒷값으로 채움
print(reindexed)
reindexed = obj3.reindex(np.arange(6), method="bfill") #뒷값을 앞값으로 채움
print(reindexed)

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object
0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
print(frame)
frame2 = frame.reindex(index = ["a", "b", "c", "d"])
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [ ]:
print(frame)
print(frame["Ohio"])
print(frame.loc["a"]) #1개의 행을 가져오는 경우도 series
print(frame.loc["a"]["Ohio"])
print(frame.loc[["a","d"]]['Ohio']) #datafrmae의 열 이름
print(frame.loc[["a","d"]][['Ohio','Texas']])

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
a    0
c    3
d    6
Name: Ohio, dtype: int64
Ohio          0
Texas         1
California    2
Name: a, dtype: int64
0
a    0
d    6
Name: Ohio, dtype: int64
   Ohio  Texas
a     0      1
d     6      7

In [ ]:
print(frame)
print(frame.loc[['a','c','d']])
print(frame.iloc[[0,1,2]])
print(frame.loc[['a','c','d']][['Ohio', 'Texas']])
#print(frame.iloc[[0,1,2]][['Ohio', 'Texas']]) #명시적 index와 암시적 index를 혼용해서 쓰지 말 것
print(frame.iloc[[0,1,2],[0,1]]) #암시적 index는 indexing을 하지 못하므로 행렬 형태로 사용해야 함

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas
a     0      1
c     3      4
d     6      7
   Ohio  Texas
a     0      1
c     3      4
d     6      7

In [ ]:
#삭제
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
print(obj)
new_obj = obj.drop("c")
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
#Dataframe
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)
newdata = data.drop(index=["Colorado", "Ohio"])
print(newdata)
newdata = data.drop(columns=["two"])
print(newdata)
newdata = data.drop("three", axis=1) #axis=1 : 열 (행기준, y축 기준)
print(newdata)
newdata = data.drop("four", axis="columns")
print(newdata)
newdata = data.drop("Ohio", axis=0) #axis=0 : 행 (열기준, x축 기준)
print(newdata)
newdata = data.drop("Colorado", axis="index") #axis=0 : 행 (열기준, x축 기준)
print(newdata)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15
          one  two  four
Ohio        0    1     3
Colorado    4    5     7
Utah        8    9    11
New York   12   13    15
          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
#Indexing, Selection, Filtering
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
print(obj)
print(obj["b"])
print(obj[1])
print(obj[2:4])
print(obj[["b", "a", "d"]])
print(obj[[1, 3]])
print(obj[obj < 2])
print(obj.loc[["b", "a", "d"]])
print(obj.iloc[[1,0,2]])
print(obj.loc["b": "c"])
print(obj.iloc[1:3]) #암시적 index와 명시적 index의 범위가 다름
obj.loc["b": "c"] = 5
print(obj)

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
1.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
a    0.0
c    2.0
dtype: float64
b    1.0
c    2.0
dtype: float64
b    1.0
c    2.0
dtype: float64
a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

/tmp/ipython-input-3153115069.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[1])
/tmp/ipython-input-3153115069.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[[1, 3]])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)
print(data["two"])
print(data[["three", "one"]])
print(data[:2]) ; print(data.iloc[:2])  #암시적 index를 사용하여 행을 가져오는 것이 가능
print(data[data["three"] > 5]) #bool index
data[data<5] = 0
print(data)
print(data.loc["Colorado"])
print(data.loc[["Colorado", "New York"]])
print(data.loc["Colorado"],["two", "three"])

print(data.iloc[2]) # 암시적 사용
print(data.iloc[[2, 1]])
print(data.iloc[2, [3, 0, 1]])
print(data.iloc[[1, 2], [3, 0, 1]])
print(data.iloc[:, :3][data.three > 5])
data.loc[data.three >= 2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64
          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15
one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64 ['two', 'three']
one       8
two       9
three    10
four     11
Name: Utah, dtype: int64
          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7
four    11
one      8
two      9
Name: Utah, dtype: int64
          four  one  two
Colorado     7    0    5
Utah        11    8    9
          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
ser = pd.Series(np.arange(3.))
print(ser)
#print(ser[-1]) # 암시적 index를 사용하는 경우에는 오류
print(ser.iloc[-1])

0    0.0
1    1.0
2    2.0
dtype: float64
2.0

In [ ]:
#산술연산과 데이터 정렬
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1, s2
print(s1+s2) #index 없으면 NaN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1, df2
print(df1+df2) #행과 열이 같은 값끼리의 연산. 일치하지 않는 경우 NaN

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:

df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
print(df1)
print(df2)
print(df1 + df2)

   A
0  1
1  2
   B
0  3
1  4
    A   B
0 NaN NaN
1 NaN NaN